[package]
name = "lucide-gpui_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = "2.0.50"
proc-macro2 = "1.0.78"
git2 = "0.18"
include_dir = "0.7.3"